project:
  type: website
  
website:
  title: "Personal Exposure & Health Data Platform"
  site-url: https://vito-epi.github.io/main
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "#catalogue"
        text: Data Catalogue
      - href: "#exchange"
        text: Data exchange
      - href: "#dashboard"
        text: EU HBM Dashboard
format:
  html:
    link-external-newwindow: true
    link-external-icon: false

