---
title: "Personal Exposure and Health Data Platform"
---

# About

The Personal Exposure and Health (PEH) Data Platform is a secure infrastructure 
developed and managed by VITO to facilitate the collection, harmonized storage, and controlled access of 
pseudonymised or anonymised single measurement data from population studies. 

The platform enables Supplying Data Controllers (SDCs) to deposit data, and Receiving Data Controllers (RDCs) to access 
approved subsets of PEH data for re-use.

The PEH Data Platform supports transparent data governance, ensures data protection and traceability, and provides operational services for data harmonisation, data 
processing, quality control, and access management. 

In addition to the exchange of single measurement data the PEH Data Platform offers additional functionalities:

- development and maintenance of FAIR data components
- collection and publication of metadata 
- calculation and publication of summary statistics


This page serves as a central entry point to services, documentation, and resources.

---

# FAIR Managament of Personal Exposure and Health Data

## Harmonisation and standardisation of Peronal Exposure and Health data {#catalogue}

Information on the **Data Catalogue** is under construction.


## GDPR proof exchange of single measurement data {#exchange}

Interact with [**https://peh.vito.be/**](https://peh.vito.be/):

- to provide individual level data
- to get access to individual level data

For information on available data and detailed user guidance, visit:

[**https://vito-epi.github.io/peh_userdocumentation/**](https://vito-epi.github.io/peh_userdocumentation/)

---
## Harmonised summary statistics of EU datasets  {#dashboard}

Interact with [**European Human Biomonitoring Dashboard**](https://hbm.vito.be/eu-hbm-dashboard):

- to browse and analyse summary statistics from Personal Exposure and Health Data
- to integrate data in the Dashboard, contact [PEHDataPlatform@vito.be](mailto:PEHDataPlatform@vito.be)


## Funding

The PEH Data Platform is developed at **VITO** in the context of environmental epidemiology and human biomonitoring research and received funding from:

- ...
- ...
- ...


## For questions or collaboration:  

Contact the PEH Data Platform managers [PEHDataPlatform@vito.be](mailto:PEHDataPlatform@vito.be)

